### ISSUE TITLE
(v5.3) Unable to convince Vuforia to generate RGB565 frames

### ISSUE THREAD

**Issue by KokeCacao** [FIRST-Tech-Challenge/SkyStone#214]
# Error Message: `FTC Unable to convince Vuforia to generate RGB565 frames!`

# Using:
 - ftc_app version: 5.3 Skystone
 - 2 Rev Extension Hub
 - motorola HT1064 [Moto G (2nd Generation)]
 - Android version: 6.0
 - Logitech HD Webcam C310, Calibrated by by Robert Atkinson, 2018.05.30 using 3DF Zephyr
powered USB Hub with 5V power bank (you can search these on Amazon)
 - Run unsuccessfully in example code `ConceptTensorFlowObjectDetectionWebcam` with `VUFORIA_KEY` adjusted with external camera
 - Run successfully without the external camera
 - `Webcam 1` was configured in the driver phone's app
 - Wireing:
   - Expansion Hub -> USB Hub
   - USB Hub <- Driver Station
   - USB Hub <- Camera
   - USB Hub <- 5V Powerbank

# Relevant Error Log:
```
01-27 11:41:10.433 16020 16716 D Uvc     : [NativeVuforiaWebcam.h:515] NativeVuforiaWebcam::supportsExposureValue()...
01-27 11:41:10.433 16020 16716 D Uvc     : [NativeVuforiaWebcam.h:515] ...NativeVuforiaWebcam::supportsExposureValue()
01-27 11:41:10.433 16020 16716 D Uvc     : [NativeVuforiaWebcam.h:579] NativeVuforiaWebcam::supportsFocusValue()...
01-27 11:41:10.434 16020 16716 D Uvc     : [NativeVuforiaWebcam.h:579] ...NativeVuforiaWebcam::supportsFocusValue()
01-27 11:41:10.438 16020 16716 I AR      : ObjectTracker: This device doesn't support model targets extended tracking, extended tracking will be turned off
01-27 11:41:10.438 16020 16716 E Vuforia : CameraDevice.getInstance.init() failed
01-27 11:41:10.440 16020 16716 E Vuforia : enableConvertFrameToBitmap(): internal error: setFrameFormat(1) failed
01-27 11:41:10.441 16020 16716 E Vuforia : enableConvertFrameToBitmap(): internal error: setFrameFormat(8) failed
01-27 11:41:10.441 16020 16716 V RobotCore: thread: ...terminating 'LinearOpMode main'
01-27 11:41:10.444 16020 16648 E EventLoopManager: Event loop threw an Exception
01-27 11:41:10.444 16020 16648 E EventLoopManager: java.lang.RuntimeException: Unable to convince Vuforia to generate RGB565 frames!
01-27 11:41:10.445 16020 16648 E EventLoopManager: 	at org.firstinspires.ftc.robotcore.internal.tfod.VuforiaFrameGenerator.<init>(VuforiaFrameGenerator.java:44)
01-27 11:41:10.445 16020 16648 E EventLoopManager: 	at org.firstinspires.ftc.robotcore.internal.tfod.TFObjectDetectorImpl.<init>(TFObjectDetectorImpl.java:130)
01-27 11:41:10.446 16020 16648 E EventLoopManager: 	at org.firstinspires.ftc.robotcore.internal.system.ClassFactoryImpl.createTFObjectDetector(ClassFactoryImpl.java:87)
01-27 11:41:10.447 16020 16648 E EventLoopManager: 	at org.firstinspires.ftc.robotcontroller.external.samples.ConceptTensorFlowObjectDetectionWebcam.initTfod(ConceptTensorFlowObjectDetectionWebcam.java:167)
01-27 11:41:10.447 16020 16648 E EventLoopManager: 	at org.firstinspires.ftc.robotcontroller.external.samples.ConceptTensorFlowObjectDetectionWebcam.runOpMode(ConceptTensorFlowObjectDetectionWebcam.java:94)
01-27 11:41:10.448 16020 16648 E EventLoopManager: 	at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper$1.run(LinearOpMode.java:305)
01-27 11:41:10.448 16020 16648 E EventLoopManager: 	at com.qualcomm.robotcore.util.ThreadPool.logThreadLifeCycle(ThreadPool.java:737)
01-27 11:41:10.448 16020 16648 E EventLoopManager: 	at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper.run(LinearOpMode.java:300)
01-27 11:41:10.449 16020 16648 E EventLoopManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-27 11:41:10.449 16020 16648 E EventLoopManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-27 11:41:10.450 16020 16648 E EventLoopManager: 	at com.qualcomm.robotcore.util.ThreadPool$ThreadFactoryImpl$1.run(ThreadPool.java:793)
01-27 11:41:10.451 16020 16648 E EventLoopManager: 	at java.lang.Thread.run(Thread.java:818)
01-27 11:41:10.451 16020 16648 V RobotCore: RobotCoreException in EventLoopManager: EventLoop Exception in loop(): RuntimeException - Unable to convince Vuforia to generate RGB565 frames!
01-27 11:41:10.451 16020 16648 V RobotCore: EventLoopManager state is EMERGENCY_STOP
01-27 11:41:10.451 16020 16648 V RobotCore: Robot Status: EMERGENCY STOP
01-27 11:41:10.451 16020 16648 D RobotCore: system telemetry: key=$System$Error$ msg="User code threw an uncaught exception: RuntimeException - Unable to convince Vuforia to generate RGB565 frames!"
01-27 11:41:10.452 16020 16648 I FtcEventLoop: ======= TEARDOWN =======
01-27 11:41:10.458 16020 16648 D Uvc     : [NativeVuforiaWebcam.cpp:241] Java_org_firstinspires_ftc_robotcore_internal_vuforia_externalprovider_VuforiaWebcam_nativePreVuforiaDeinit()...
01-27 11:41:10.458 16020 16648 D Uvc     : [NativeVuforiaWebcam.h:246] NativeVuforiaWebcam::preVuforiaDeinit()...
01-27 11:41:10.458 16020 16648 D Uvc     : [NativeVuforiaWebcam.h:246] ...NativeVuforiaWebcam::preVuforiaDeinit()
01-27 11:41:10.458 16020 16648 D Uvc     : [NativeVuforiaWebcam.cpp:241] ...Java_org_firstinspires_ftc_robotcore_internal_vuforia_externalprovider_VuforiaWebcam_nativePreVuforiaDeinit()
01-27 11:41:10.458 16020 16648 D Vuforia : Vuforia.deinit()...
01-27 11:41:10.460 16020 16650 V Robocol : sending CMD_STREAM_CHANGE(629), attempt: 0
01-27 11:41:10.461 16020 16650 V Robocol : sending CMD_NOTIFY_ROBOT_STATE(630), attempt: 0
01-27 11:41:10.461 16020 16650 V Robocol : sending CMD_STREAM_CHANGE(632), attempt: 0
01-27 11:41:10.463 16020 16648 D Vuforia : ...Vuforia.deinit()
01-27 11:41:10.463 16020 16648 D Uvc     : [NativeVuforiaWebcam.cpp:258] Java_org_firstinspires_ftc_robotcore_internal_vuforia_externalprovider_VuforiaWebcam_nativePostVuforiaDeinit()...
01-27 11:41:10.463 16020 16648 D Uvc     : [NativeVuforiaWebcam.cpp:258] ...Java_org_firstinspires_ftc_robotcore_internal_vuforia_externalprovider_VuforiaWebcam_nativePostVuforiaDeinit()
01-27 11:41:10.464 16020 16648 V NativeVuforiaWebcam: destroy(pointer=0xb8e5b190)
01-27 11:41:10.464 16020 16648 D Uvc     : [NativeVuforiaWebcam.cpp:203] Java_org_firstinspires_ftc_robotcore_internal_vuforia_externalprovider_VuforiaWebcam_nativeReleaseVuforiaWebcam()...
01-27 11:41:10.464 16020 16648 D UvcVuforiaWebcam: [NativeVuforiaWebcam.cpp:206] NativeVuforiaWebcam cref remaining=1
01-27 11:41:10.464 16020 16648 D Uvc     : [NativeVuforiaWebcam.cpp:203] ...Java_org_firstinspires_ftc_robotcore_internal_vuforia_externalprovider_VuforiaWebcam_nativeReleaseVuforiaWebcam()
01-27 11:41:10.475 16020 16648 I RobotCore: ******************** STOP - OPMODE /storage/emulated/0/FIRST/matchlogs/Match-0-Concept:_TensorFlow_Object_Detection_Webcam.txt ********************
01-27 11:41:10.478 16020 16648 I RobotCore: Pruning old logs deleting Match-0-Concept:_TensorFlow_Object_Detection_Webcam.txt
01-27 11:41:10.485 16020 16750 I RobotCore: saving match logcat to /storage/emulated/0/FIRST/matchlogs/Match-0-Concept:_TensorFlow_Object_Detection_Webcam.txt
01-27 11:41:10.485 16020 16750 I RobotCore: logging command line: exec logcat -d -T '1-27 11:41:8.000' -f /storage/emulated/0/FIRST/matchlogs/Match-0-Concept:_TensorFlow_Object_Detection_Webcam.txt -n4 -v threadtime UsbRequestJNI:S UsbRequest:S art:W ThreadPool:W System:W ExtendedExtractor:W OMXClient:W MediaPlayer:W dalvikvm:W  *:V
01-27 11:41:10.516 16020 16191 V SoundInfo: construct(0x0a0e262a)
01-27 11:41:10.584 16020 16190 D ExtendedUtils: extended extractor not needed, return default
01-27 11:41:10.615 16020 16756 E OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
01-27 11:41:10.647 16020 16750 I RobotCore: Done running exec logcat -d -T '1-27 11:41:8.000' -f /storage/emulated/0/FIRST/matchlogs/Match-0-Concept:_TensorFlow_Object_Detection_Webcam.txt -n4 -v threadtime UsbRequestJNI:S UsbRequest:S art:W ThreadPool:W System:W ExtendedExtractor:W OMXClient:W MediaPlayer:W dalvikvm:W  *:V
01-27 11:41:10.647 16020 16750 I RobotCore: exiting match logcat for /storage/emulated/0/FIRST/matchlogs/Match-0-Concept:_TensorFlow_Object_Detection_Webcam.txt
```

# Things I have tried:
 - power the camera with a power bank
 - not power the camera with a power bank
 - I checked that the camera actually receive power by replacing the camera with a phone, and we see that the phone is charging
 - I saw the solution [HERE](https://github.com/FIRST-Tech-Challenge/skystone/wiki/Troubleshooting#problem-with-uvc-webcam-support-and-version-52-software-listed-092019), but v5.3 already implemented the solution so there is no need to change the configure in `build.common.gradle`
 - tried to reconfigure by re-scanning and save `Webcam 1`

# Other Relevant Posts:
 - https://www.reddit.com/r/FTC/comments/arak5b/runtime_exception_unable_to_convince_vuforia_to/
 - https://www.reddit.com/r/FTC/comments/dfpuhx/unable_to_convince_vuforia_to_use_rgb565_frames/

**Comment by KokeCacao** [comment]
Full Error From the Robot Controller: https://pastebin.com/03XKfCVW
Full Error From the Driver Station: https://pastebin.com/8GJaCN5B

**Comment by KokeCacao** [comment]
Ref:
[robotControllerLog_robot.txt](https://github.com/FIRST-Tech-Challenge/SkyStone/files/4118671/robotControllerLog_robot.txt)
[robotControllerLog_driver.txt](https://github.com/FIRST-Tech-Challenge/SkyStone/files/4118672/robotControllerLog_driver.txt)

**Comment by ssysm** [comment]
Have you tried connecting the USB Camera directly to the phone and see if it works? Some USB Hub isn't fast enough to handle the camera data.

**Comment by KokeCacao** [comment]
> Have you tried connecting the USB Camera directly to the phone and see if it works? Some USB Hub isn't fast enough to handle the camera data.

The problem is solved! Thank you so much!

# Solution
I tested with a couple of USB hubs and found out some works on the Android phone and some are not. Specifically: [This one on Amazon](https://www.amazon.com/gp/product/B07GLJ1XBW/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1) does not work although it says "high speed."

According to the [documentation](https://github.com/ftctechnh/ftc_app/wiki/Using-an-External-UVC-Camera-and-a-Powered-USB-Hub), a good USB hub should have `Supports a data transfer rate of 480Mbps.`

I am purchasing [this one](https://www.amazon.com/Unitek-Charging-Extension-Connector-Compatible/dp/B07G9CXSW1/ref=sr_1_9?keywords=micro%2Busb%2Bhub%2Bpowered&qid=1580164785&refinements=p_72%3A2661618011&rnid=2661617011&sr=8-9&th=1) since I can't use the [recommended](https://www.amazon.com/Anker-Ultra-Slim-Portable-Adapter-Notebook/dp/B0192LPK5M/ref=sr_1_1?s=electronics&ie=UTF8&qid=1543857698&sr=1-1&keywords=Anker+4-Port+USB+3.0+Ultra-Slim+Portable+Data+Hub+with+12W+Power+Adapter+for+MacBook%2C+Mac+Pro%2FMini%2C+iMac%2C+XPS%2C+Surface+Pro%2C+Notebook+PCs+and+More) USB hub due to incompatibility with USB-C 

# Ways to test camera on Android phone
(for future ref)
1. Download the app "USB Camera - Connect EasyCap or USB WebCam"
2. Test it by directly plug WebCam into Andoid phone without extra power.
